name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: make deps

      - name: Build
        run: make build-linux

      - name: Run unit tests
        run: make unit-test

      - name: Run integration tests
        run: make integration-test

      - name: Run performance tests
        run: make performance-test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: goproxy
          path: goproxy

  release:
    name: Create Release
    needs: build

    #NOTE: This will run on every push to main
    if: github.ref == 'refs/heads/main' 

    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: "1.22.1" # Make sure this matches the version in your build job
        - name: Build project
          run: make build-linux
        - name: Create Release
          uses: softprops/action-gh-release@v1 # Use this action instead
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: ./goproxy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
